### 1) Create student (valid) -> 201
POST http://localhost:8082/api/students
Content-Type: application/json

{
  "id": "S1",
  "name": "Asha",
  "email": "asha@example.com"
}


### 2) Create student (duplicate id) -> 409
POST http://localhost:8082/api/students
Content-Type: application/json

{
  "id": "S1",
  "name": "Asha Again",
  "email": "asha2@example.com"
}


### 3) Create student (missing fields) -> 400
POST http://localhost:8082/api/students
Content-Type: application/json

{
  "id": "",
  "name": "No Email"
}


### 4) Create student (bad id) -> 400
POST http://localhost:8082/api/students
Content-Type: application/json

{
  "id": "1",
  "name": "Bad Id",
  "email": "badid@example.com"
}


### 5) Create student (bad email) -> 400
POST http://localhost:8082/api/students
Content-Type: application/json

{
  "id": "S2",
  "name": "Bad Email",
  "email": "not-an-email"
}


### 6) Get existing student -> 200
GET http://localhost:8082/api/students/S1
Accept: application/json


### 7) Get missing student -> 404
GET http://localhost:8082/api/students/S999
Accept: application/json
